### ISSUE TITLE
Soon, Kind of Soon, Not Soon Buttons

### ISSUE THREAD

**Issue by danainjax** [the-collab-lab/tcl-37-smart-shopping-list#41]
Create Soon, Kind of Soon, Not Soon Button Component(s) for the Add Item page 

![image](https://user-images.githubusercontent.com/67841237/155779607-14d28432-b7b1-4b73-b793-4e71209609cc.png)
/* Rectangle 171 */

position: absolute;
width: 100px;
height: 81px;
left: 696px;
top: 106px;

background: rgba(222, 244, 221, 0.5);
border-radius: 14px;
/* Rectangle 172 */

position: absolute;
width: 100px;
height: 81px;
left: 813px;
top: 106px;

background: #FAFADF;
border-radius: 14px;
/* Rectangle 173 */

position: absolute;
width: 100px;
height: 81px;
left: 930px;
top: 106px;

background: rgba(248, 231, 221, 0.5);
border-radius: 14px;

**Comment by sanrafa** [comment]
Merged into #52 for staging.
