### ISSUE TITLE
Input field component

### ISSUE THREAD

**Issue by danainjax** [the-collab-lab/tcl-37-smart-shopping-list#42]
Create input field component for : three word token, item, and search
![image](https://user-images.githubusercontent.com/67841237/155783117-5eb6ca37-d9a8-41e9-a285-7a0c4644f699.png)

![image](https://user-images.githubusercontent.com/67841237/155783757-bc55fd66-b459-4f18-86c0-85ddec72be4d.png)

![image](https://user-images.githubusercontent.com/67841237/155783850-78a681a8-b72f-4444-afdd-6f752bf4b45b.png)

/* Input / Text Input */

position: relative;
width: 327px;
height: 54px;

background: #F3F4F4;
border-radius: 9.24771px;

/* Placeholder */

position: absolute;
visibility: hidden;
left: 24.22px;
right: 24.22px;
top: 18.17px;
bottom: 18.17px;

/* Text / 16px Regular */
font-family: Roboto Mono;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 21px;
display: flex;
align-items: center;

/* Grey */
color: #CDCDCD;

/* Item */

position: absolute;
left: 24.22px;
right: 24.22px;
top: 18.17px;
bottom: 18.17px;

font-family: Poppins;
font-style: normal;
font-weight: normal;
font-size: 24.2222px;
line-height: 36px;
display: flex;
align-items: center;

color: #9E9EA7;

/* Input / Text Input */

position: absolute;
width: 327px;
height: 54px;
left: 521px;
top: 457px;

background: #F3F4F4;
border-radius: 9.24771px;

/* Placeholder */

position: absolute;
visibility: hidden;
left: 24.22px;
right: 24.22px;
top: 18.17px;
bottom: 18.17px;

/* Text / 16px Regular */
font-family: Roboto Mono;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 21px;
display: flex;
align-items: center;

/* Grey */
color: #CDCDCD;

/* Item */

position: absolute;
left: 24.22px;
right: 24.22px;
top: 18.17px;
bottom: 18.17px;

font-family: Poppins;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 24px;
display: flex;
align-items: center;

color: #9E9EA7;

/* Input / Text Input */

position: absolute;
width: 327px;
height: 54px;
left: 521px;
top: 449.67px;

/* White */
background: #FFFFFF;
border: 2.6422px solid rgba(118, 221, 120, 0.5);
box-sizing: border-box;
border-radius: 9.24771px;

/* Placeholder */

position: absolute;
visibility: hidden;
left: 24.22px;
right: 24.22px;
top: 18.17px;
bottom: 18.17px;

/* Text / 16px Regular */
font-family: Roboto Mono;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 21px;
display: flex;
align-items: center;

/* Grey */
color: #CDCDCD;

/* Item */

position: absolute;
left: 24.22px;
right: 24.22px;
top: 18.17px;
bottom: 18.17px;

font-family: Poppins;
font-style: normal;
font-weight: normal;
font-size: 24.2222px;
line-height: 36px;
display: flex;
align-items: center;

/* Black */
color: #000000;

![image](https://user-images.githubusercontent.com/67841237/155783987-29364eac-cb5e-4e19-b5b1-552978dcecbe.png)
![image](https://user-images.githubusercontent.com/67841237/155784051-dfad6242-6d96-4410-888e-6e47c211027d.png)
![image](https://user-images.githubusercontent.com/67841237/155784099-5c6b564b-8bf2-4d0a-8e59-e71abbaa0bcc.png)

**Comment by sanrafa** [comment]
Component has been merged from separate branch, #53
